### PR TITLE
goversion: improve portability

### PR DESCRIPTION
**Pull request by rivy**
* adds compatibility for `GOOS == "windows"`

### CODE REVIEW

**Comment by rivy** [comment]
I hope you'll excuse any idiomatic errors... I'm quite new to `go`.

I'm happy to rework the PR if needed.

**Comment by rivy** [comment]
@rsc, any concern about this that I need to rework?

**Comment by rsc** [comment]
Sorry for dropping this. I'll push an alternate approach that avoids the os/exec.

**Comment by rivy** [comment]
I initially implemented it similarly, and e2aeda8 fixes the issue for `GOOS="windows"`. But, I thought it might be improved by being more "generally portable" using `GOEXE` (though I am unsure if it's even used on any other platform). However, I couldn't find access to the `GOEXE` value except via os/exec. 

Being new to `go`, I'd appreciate any thoughts on the matter for future reference.

Thanks for the reply / fix.

**Comment by rsc** [comment]
cmd/go/internal/envcmd/env.go sets GOEXE using cfg.ExeSuffix, which is set in cmd/go/internal/cfg/cfg.go. I don't anticipate any other similar exceptions, and this is far from the only piece of code that knows this detail. Windows is just special.

**Pull request closed without merging**
